version: "3.9"

# Inject env vars at runtime by entering 'docker-compose --env-file .env.local up [--detach] [--force-recreate] [--renew-anon-volumes]'
services:
    app:
        image: express-movers-docker:latest
        build:
            context: .
            args:
                - SERVICE_PORT=$SERVICE_PORT
        ports:
            - 3000:${SERVICE_PORT}
        container_name: express_app
