databaseChangeLog:
  - changeSet:
      id: 1
      author: prathameshk
      changes:
        - createTable:
            tableName: messages
            columns:
              - column:
                  name: id
                  type: uuid
                  defaultValueComputed: gen_random_uuid()
                  constraints:
                    primaryKey: true
                    nullable: false
              - column:
                  name: message_content
                  type: varchar(255)

  # TODO: Migrate each changeset to its own file and reference file in master changeset
  - changeSet:
      id: 2
      author: prathameshk
      changes:
        - insert:
            tableName: messages
            columns:
              - column:
                  name: message_content
                  value: Hello from Liquibase!
        - insert:
            tableName: messages
            columns:
              - column:
                  name: message_content
                  value: Goodbye from Liquibase!
